### ISSUE TITLE
Autor do Commit

### ISSUE THREAD

**Issue by maico910** [caio-ribeiro-pereira/selic#13]
Isso não é exatamente um Issue, foi só uma pequena bobagem que eu fiz, eu percebi q os commits anteriores que eu fiz estão com um email errado, o email deveria ser `maico910@gmail.com` ao invés do email que comeca com `michael.wu`, entendo q é complicado alterar o histórico, mas poderia avaliar a possibilidade de alterar isso? obrigado

**Comment by caio-ribeiro-pereira** [comment]
@maico910 onde esta aparecendo isso?

**Comment by maico910** [comment]
se você for olhar commits meus antes da data Oct 30, 2021, vc vai ver q ta como um foto padrão (Ghost User), e clicando nele não vai redirecionar para o meu perfil, eu confirmei com um amigo meu isso ocorreu pq qnd dei commit, ele usou um email diferente da minha conta atual

![image](https://user-images.githubusercontent.com/24510745/140445207-3eda76c8-e35d-4451-a2ae-8d682becb0af.png)

**Comment by maico910** [comment]
se você permitir, eu msm faço esse retrabalho de corrigir o autor do commit, só que dai eu acho vai acabar apagando do histórico os PRs, caso você não se importar com isso, é claro

**Comment by caio-ribeiro-pereira** [comment]
@maico910 isso é config do seu próprio git e essa visualização só acontece para você, pois aqui esta aparecendo seu nick maico910 com foto normalmente.

Sem contar que apagar histórico desse repositório não aceito, pois já existem galera usando essa lib, acredito que qualquer atualização do seu perfil, o github vai atualizar o nick no histórico normalmente.

Vou fechar essa issue pois não há o que fazer no repositório.

**Comment by maico910** [comment]
o seu está aparecendo normal? os ultimos commits meu está normal msm, somente os anteriores está zuado mesmo, de qlqr forma, obrigado pelo feedback

**Comment by caio-ribeiro-pereira** [comment]
Sugiro que vc veja no comando git config como editar nome e email na sua máquina pra deixar organizado isso, pois caso vc tenha feito commits em mais de uma máquina, cada máquina pode estar com git config diferente e isso pode refletir sim em nome diferente da mesma conta, porém o q importa é o github linkando pro mesma conta mesmo q apareça nomes diferentes

**Comment by maico910** [comment]
isso já foi corrigido já, os commits anteriores tbm estão linknados na minha conta para voce?

**Comment by caio-ribeiro-pereira** [comment]
Em qual página exatamente devo ver aqui?

**Comment by maico910** [comment]
se voce ir no commit 6148770, vai ver q vai conseguir clicar no meu nome, mas se for exemplo no e4009fc, não vai conseguir, pelo o que eu entendi pq qnd fiz akele commit ele não está linkado na minha conta

**Comment by caio-ribeiro-pereira** [comment]
Aaah entendi, e realmente não esta abrindo quando esta Michael Wu, porém vc fez diversos PRs significativos com seu username correto, apagar histórico não vai ser legal pro repositório, como vc ja corrigiu isso, vamos manter assim, combinado?
