### ISSUE TITLE
Opção de alterar cdiScore e poupancaPercent

### ISSUE THREAD

**Issue by maico910** [caio-ribeiro-pereira/selic#7]
Acho interessante a ideia de poder alterar os parâmetros `cdiScore` e `poupancaPercent` para poder de simulação por exemplo

**Comment by caio-ribeiro-pereira** [comment]
@maico910 o próprio construtor da classe Selic já esta planejado para alteração desses parâmetros, eu só não documentei isso, pois em breve vou implementar um jeito mais preciso de obter cdi e calcular corretamente a taxa da poupança sobre a selic, pois descobri que existem regras que vão além dos 70% da selic

**Comment by maico910** [comment]
@caio-ribeiro-pereira pelo o que eu entendi, do jeito que está só dá para alterar no construtor não é? caso puder alterar o parâmetro sem criar uma nova instância, pode ser interessante para pessoas que querem fazer simulação de % de taxa diferente por exemplo

**Comment by caio-ribeiro-pereira** [comment]
@maico910 esses parâmetros serão removidos assim que eu implementar o jeito certo de obter cdi e poupança, por enquanto foi uma solução temporária que fiz por falta de conhecimento sobre essas taxas

**Comment by Pacheco95** [comment]
> Quando a taxa básica de juros está igual ou abaixo de 8,5% ao ano, a poupança rende 70% da Selic mais a variação da TR (Taxa Referencial), que hoje está zerada, o que dá cerca de 0,44% ao mês. Já quando a Selic ultrapassa 8,5%, ela volta a render pela regra antiga, de 0,5% ao mês mais TR.

https://www.cnnbrasil.com.br/business/rendimento-da-poupanca-muda-com-nova-alta-da-selic-entenda-as-novas-regras/#:~:text=Quando%20a%20taxa%20b%C3%A1sica%20de%20juros%20est%C3%A1%20igual%20ou%20abaixo,5%25%20ao%20m%C3%AAs%20mais%20TR.

**Comment by caio-ribeiro-pereira** [comment]
@Pacheco95 por decisões de manter a lib mais enxuta, a nova versão só foca em pegar dados do cdi pelo site cetip e selic, assim, se precisar gerar taxa de poupança, é só pegar taxa selic e fazer o cálculo por conta própria, e assim mantenho a lib mais leve e focada apenas em pegar dados de diversas fontes, sugiro que teste a última versão

**Comment by Pacheco95** [comment]
Estou fazendo isso mesmo. Quando conseguir eu aviso

**Comment by Pacheco95** [comment]
Parece que deu certo. https://bit.ly/3naBeP0
Coloquei o link com o bitly pq não quero que o link seja indexado nos motores de busca
