### ISSUE TITLE
Uso de Selic na memória

### ISSUE THREAD

**Issue by maico910** [caio-ribeiro-pereira/selic#8]
Como as alterações de Selic não acontece com muita frequência, pode ser interessante ao invés de sempre chamar API do BCB, criar um `tempo de validade` ou usar o primeiro valor adquirido pela API como a base do cálculo

**Comment by caio-ribeiro-pereira** [comment]
@maico910 concordo na implementação de cache, porém pensando em deixar essa lib o mais simples, acho valido não ter isso no projeto e sim deixar o caching como responsabilidade de quem for usar essa lib, assim cada um implementa solução de cache que desejar, sem contar que em casos de testes isso pode causar mais dor de cabeça em quem usar a lib e realmente precisar dos dados vindo de uma request
